force-app/main/default/objects/Customer_Portfolio__c/Customer_Portfolio__c.object-meta.xml
<CustomObject>
    <description>Represents the link between Users and Accounts.
This object stores information about whether access is direct (External) or inherited (Internal), and allows access propagation logic to operate based on the role hierarchy.</description>
    <label>Customer Portfolio</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Customer Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Portfolio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portfolio__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The customer to which the user has access.</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers Portfolio</relationshipLabel>
    <relationshipName>Customers_Portfolio</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>ID used for integration and deduplication.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates how the user was granted access to the customer.</description>
    <inlineHelpText>&quot;External&quot; is only for access given by the third-party system. 
&quot;Internal&quot; is only for access inherited via role hierarchy.</inlineHelpText>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who currently has access to the customer.</description>
    <inlineHelpText>The user who currently has access to the customer.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers_Portfolio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static Account createAccount(String name) {
        return new Account(Name = name);
    }
    /**
* @description Cria um utilizador com um papel específico.
* @param name Role name.
* @param parentRoleId Parent role Id.
* @return Inserted User Role.
*/
    public static User createUser(String alias, UserRole role) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        String uniqueTimestamp = String.valueOf(Datetime.now().getTime()) + alias;
        
        User u = new User(
            Alias = alias,
            Email = alias + '@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test ' + alias,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = alias + '.' + uniqueTimestamp + '@test.com',
            UserRoleId = role.Id
        );
        return u;
    }
    
    /**
* @description Creates and  inserts a User Role.
* @param name Role name.
* @param parentRoleId Parent role Id.
* @return Inserted User Role.
*/    
    public static Customer_Portfolio__c createPortfolio(Id accountId, Id userId, String source) {
        return new Customer_Portfolio__c(
            Customer__c = accountId,
            User__c = userId,
            Source__c = source,
            External_Id__c = userId + '' + accountId
        );
    }
    
    /**
* @description Creates and  inserts a User Role.
* @param name Role name.
* @param parentRoleId Parent role Id.
* @return Inserted User Role.
*/
    public static UserRole createRole(String name, Id parentRoleId) {
        UserRole role = new UserRole(Name = name, ParentRoleId = parentRoleId);
        insert role;
        return role;
    }
    
    /**
* @description Creates and inserts a role hierarchy with a list of roles.
* @param roleNames A list with role names, from the top one to the bottom one.
* @return Inserted users list.
*/
    public static List<UserRole> createRoleHierarchy(List<String> roleNames) {
        List<UserRole> createdRoles = new List<UserRole>();
        Id parentId = null;
        for (String roleName : roleNames) {
            UserRole newRole = createRole(roleName, parentId);
            createdRoles.add(newRole);
            parentId = newRole.Id;
        }
        return createdRoles;
    }
}