force-app/main/default/objects/Customer_Portfolio__c/Customer_Portfolio__c.object-meta.xml
<CustomObject>
    <description>Represents the link between Users and Accounts.
This object stores information about whether access is direct (External) or inherited (Internal), and allows access propagation logic to operate based on the role hierarchy.</description>
    <label>Customer Portfolio</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Customer Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Portfolio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portfolio__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The customer to which the user has access.</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers Portfolio</relationshipLabel>
    <relationshipName>Customers_Portfolio</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates how the user was granted access to the customer.</description>
    <inlineHelpText>&quot;External&quot; is only for access given by the third-party system. 
&quot;Internal&quot; is only for access inherited via role hierarchy.</inlineHelpText>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who currently has access to the customer.</description>
    <inlineHelpText>The user who currently has access to the customer.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers_Portfolio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerPortfolioDeleteBatch.cls
/**
* @description Batch to process the Custom Portfolio deletion. When a
* record with Source = 'External' is deleted, this batch searches for
* corresponding records with Source = 'Internal' in the role hierarchy .
*/
public class CustomerPortfolioDeleteBatch implements Database.Batchable<SObject> {
/**
* @description Iniciates the batch. Searches for Customer Portfolio records 
* with Source = 'External' that were deleted recently.
*/    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Datetime startTimeWindow = Datetime.now().addHours(-3);    
        String query = 'SELECT User__c, Customer__c FROM Customer_Portfolio__c ' +
            'WHERE Source__c = \'External\' AND IsDeleted = true AND LastModifiedDate >= :startTimeWindow' +
            ' ALL ROWS';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Customer_Portfolio__c> scope) {
        Set<Id> userIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        
        for (Customer_Portfolio__c cp : scope) {
            userIds.add(cp.User__c);
            accountIds.add(cp.Customer__c);
        }
        if (userIds.isEmpty()) {
            return;
        }
        
        Set<Id> superiorUserIds = RoleHierarchyHelper.getSuperiorUserIds(userIds);
        if (superiorUserIds.isEmpty()) {
            return;
        }
        List<Customer_Portfolio__c> internalsToDelete = [
            SELECT Id FROM Customer_Portfolio__c
            WHERE Source__c = 'Internal'
            AND Customer__c IN :accountIds
            AND User__c IN :superiorUserIds
        ];
        
        if (!internalsToDelete.isEmpty()) {
            Database.delete(internalsToDelete, false);
        }
    }
public void finish(Database.BatchableContext bc) {
    System.debug('CustomerPortfolioDeleteBatch succeeded. Job ID: ' + bc.getJobId());
    if (!Test.isRunningTest()) {
         Database.executeBatch(new CustomerPortfolioUpsertBatch());
         System.debug('Starting the Upsert Batch');
    }
}
}